# Generated by Django 4.1 on 2023-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("file", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InformationSubject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("teache_id", models.BigIntegerField()),
                ("url_online_education", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("teacher_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("login", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("point", models.IntegerField(null=True)),
                ("is_teacher", models.BooleanField()),
            ],
        ),
    ]
