# Generated by Django 4.1 on 2023-11-27 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teamsClone", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
