# Generated by Django 4.2.7 on 2023-12-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0003_finishedhomework_group_grouptask_homework_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file_byte',
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsClone.group'),
        ),
    ]
