# Generated by Django 4.2.7 on 2023-12-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0004_remove_task_file_byte_task_teacher_id_users_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='group_id',
            new_name='group',
        ),
    ]
