# Generated by Django 4.2.7 on 2023-12-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0006_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedhomework',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsClone.subject'),
        ),
    ]
