# Generated by Django 4.2.7 on 2023-12-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0007_finishedhomework_is_verified_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file_byte',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsClone.task'),
        ),
        migrations.DeleteModel(
            name='FinishedHomework',
        ),
    ]
