# Generated by Django 4.2.7 on 2023-12-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0008_homework_file_byte_homework_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
