# Generated by Django 4.2.7 on 2023-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0009_homework_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='work',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='users',
            name='point',
        ),
        migrations.AlterField(
            model_name='homework',
            name='is_verified',
            field=models.BooleanField(),
        ),
    ]
