# Generated by Django 4.2.7 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0010_rename_work_homework_description_remove_users_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
