# Generated by Django 4.1.3 on 2023-12-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0011_alter_homework_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsClone.users'),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='start_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='stop_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='time_delivery',
            field=models.DateField(),
        ),
    ]
