# Generated by Django 4.2.7 on 2023-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsClone', '0011_alter_homework_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='start_deadline',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='start_deadline',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='stop_deadline',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='stop_deadline',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='time_delivery',
        ),
        migrations.AddField(
            model_name='homework',
            name='time_delivery',
            field=models.DateField(),
        ),
    ]